In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np

# 2. Feature Scaling

In [2]:
data = pd.read_csv("/content/drive/MyDrive/Data Mining 2021/1. Load data & Preprocessing/01. Data Preprocessing/Data.csv")

In [3]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(data.iloc[:,1:3].values)
data.iloc[:,1:3]=imputer.transform(data.iloc[:,1:3].values)
data.head()

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes

In [5]:
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler

data = data.iloc[:,1:3]
standard_scaler = StandardScaler()
nomralizer = Normalizer()
min_max_scaler = MinMaxScaler()

#Standard scaler
print('Standarization')
print(standard_scaler.fit_transform(data))

Standarization
[[ 7.58874362e-01  7.49473254e-01]
 [-1.71150388e+00 -1.43817841e+00]
 [-1.27555478e+00 -8.91265492e-01]
 [-1.13023841e-01 -2.53200424e-01]
 [ 1.77608893e-01  6.63219199e-16]
 [-5.48972942e-01 -5.26656882e-01]
 [ 0.00000000e+00 -1.07356980e+00]
 [ 1.34013983e+00  1.38753832e+00]
 [ 1.63077256e+00  1.75214693e+00]
 [-2.58340208e-01  2.93712492e-01]]


In [6]:
#Normalizer
print('Normalizing')
print(nomralizer.fit_transform(data))

Normalizing
[[6.11110997e-04 9.99999813e-01]
 [5.62499911e-04 9.99999842e-01]
 [5.55555470e-04 9.99999846e-01]
 [6.22950699e-04 9.99999806e-01]
 [6.27177577e-04 9.99999803e-01]
 [6.03448166e-04 9.99999818e-01]
 [7.45726288e-04 9.99999722e-01]
 [6.07594825e-04 9.99999815e-01]
 [6.02409529e-04 9.99999819e-01]
 [5.52238722e-04 9.99999848e-01]]


In [7]:
#Minmax scaling
print('Minmax Scaling')
print(min_max_scaler.fit_transform(data))

Minmax Scaling
[[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739 0.45079365]
 [0.34782609 0.28571429]
 [0.51207729 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]
