In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np

# 1. Import Data dan Preprocessing

In [2]:
data = pd.read_csv("/content/drive/MyDrive/Data Mining/Data (1).csv")

In [3]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(data.iloc[:,1:3].values)
data.iloc[:,1:3]=imputer.transform(data.iloc[:,1:3].values)
data.head()

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes

## Encoding categorical data

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [6]:
lable_encoder = LabelEncoder()
temp = data.copy()
temp.iloc[:, 0] = lable_encoder.fit_transform(data.iloc[:, 0])
temp.head()

Country   Age        Salary Purchased
0        0  44.0  72000.000000        No
1        2  27.0  48000.000000       Yes
2        1  30.0  54000.000000        No
3        2  38.0  61000.000000        No
4        1  40.0  63777.777778       Yes

In [7]:
pd.get_dummies(data.iloc[:, :-1])

Age        Salary  Country_France  Country_Germany  Country_Spain
0  44.000000  72000.000000               1                0              0
1  27.000000  48000.000000               0                0              1
2  30.000000  54000.000000               0                1              0
3  38.000000  61000.000000               0                0              1
4  40.000000  63777.777778               0                1              0
5  35.000000  58000.000000               1                0              0
6  38.777778  52000.000000               0                0              1
7  48.000000  79000.000000               1                0              0
8  50.000000  83000.000000               0                1              0
9  37.000000  67000.000000               1                0              0

## Binarisasi

In [8]:
from sklearn.preprocessing import Binarizer
from sklearn.datasets import load_iris

iris_dataset = load_iris()
X = iris_dataset.data
y = iris_dataset.target
feature_names = iris_dataset.feature_names

X[:, 1:2] = Binarizer(threshold = X[:,1].mean()).fit_transform(X[:,1].reshape(-1,1))
print(X)

[[5.1 1.  1.4 0.2]
 [4.9 0.  1.4 0.2]
 [4.7 1.  1.3 0.2]
 [4.6 1.  1.5 0.2]
 [5.  1.  1.4 0.2]
 [5.4 1.  1.7 0.4]
 [4.6 1.  1.4 0.3]
 [5.  1.  1.5 0.2]
 [4.4 0.  1.4 0.2]
 [4.9 1.  1.5 0.1]
 [5.4 1.  1.5 0.2]
 [4.8 1.  1.6 0.2]
 [4.8 0.  1.4 0.1]
 [4.3 0.  1.1 0.1]
 [5.8 1.  1.2 0.2]
 [5.7 1.  1.5 0.4]
 [5.4 1.  1.3 0.4]
 [5.1 1.  1.4 0.3]
 [5.7 1.  1.7 0.3]
 [5.1 1.  1.5 0.3]
 [5.4 1.  1.7 0.2]
 [5.1 1.  1.5 0.4]
 [4.6 1.  1.  0.2]
 [5.1 1.  1.7 0.5]
 [4.8 1.  1.9 0.2]
 [5.  0.  1.6 0.2]
 [5.  1.  1.6 0.4]
 [5.2 1.  1.5 0.2]
 [5.2 1.  1.4 0.2]
 [4.7 1.  1.6 0.2]
 [4.8 1.  1.6 0.2]
 [5.4 1.  1.5 0.4]
 [5.2 1.  1.5 0.1]
 [5.5 1.  1.4 0.2]
 [4.9 1.  1.5 0.2]
 [5.  1.  1.2 0.2]
 [5.5 1.  1.3 0.2]
 [4.9 1.  1.4 0.1]
 [4.4 0.  1.3 0.2]
 [5.1 1.  1.5 0.2]
 [5.  1.  1.3 0.3]
 [4.5 0.  1.3 0.3]
 [4.4 1.  1.3 0.2]
 [5.  1.  1.6 0.6]
 [5.1 1.  1.9 0.4]
 [4.8 0.  1.4 0.3]
 [5.1 1.  1.6 0.2]
 [4.6 1.  1.4 0.2]
 [5.3 1.  1.5 0.2]
 [5.  1.  1.4 0.2]
 [7.  1.  4.7 1.4]
 [6.4 1.  4.5 1.5]
 [6.9 1.  4.

In [9]:
from sklearn.preprocessing import StandardScaler, Normalizer, MinMaxScaler

data = data.iloc[:,1:3]
standard_scaler = StandardScaler()
nomralizer = Normalizer()
min_max_scaler = MinMaxScaler()

#Standard scaler
print('Standarization')
print(standard_scaler.fit_transform(data))

Standarization
[[ 7.58874362e-01  7.49473254e-01]
 [-1.71150388e+00 -1.43817841e+00]
 [-1.27555478e+00 -8.91265492e-01]
 [-1.13023841e-01 -2.53200424e-01]
 [ 1.77608893e-01  6.63219199e-16]
 [-5.48972942e-01 -5.26656882e-01]
 [ 0.00000000e+00 -1.07356980e+00]
 [ 1.34013983e+00  1.38753832e+00]
 [ 1.63077256e+00  1.75214693e+00]
 [-2.58340208e-01  2.93712492e-01]]


In [10]:
#Normalizer
print('Normalizing')
print(nomralizer.fit_transform(data))

Normalizing
[[6.11110997e-04 9.99999813e-01]
 [5.62499911e-04 9.99999842e-01]
 [5.55555470e-04 9.99999846e-01]
 [6.22950699e-04 9.99999806e-01]
 [6.27177577e-04 9.99999803e-01]
 [6.03448166e-04 9.99999818e-01]
 [7.45726288e-04 9.99999722e-01]
 [6.07594825e-04 9.99999815e-01]
 [6.02409529e-04 9.99999819e-01]
 [5.52238722e-04 9.99999848e-01]]


In [11]:
#Minmax scaling
print('Minmax Scaling')
print(min_max_scaler.fit_transform(data))

Minmax Scaling
[[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739 0.45079365]
 [0.34782609 0.28571429]
 [0.51207729 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]
